require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.impatient"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.lualine"
require "user.indentline"
require "user.autocommands"
require "user.fidget"
require "user.asciidoctor"
require "user.markdown-preview"
require "user.rust-setup"
require "user.whichkey"
require "user.nvimtree"
vim.g.markdown_fenced_languages = {
  "mermaid=mermaid"
}
